postgres:
  user: "khan_tet"
  dbName: "khan_test"
  host: "localhost"
  port: 5433
  sslMode: "disable"

newrelic:
  key: ""

jaeger:
  disabled: false
  samplingProbability: 1.0

 extensions:
  dogstatsd:
    host: localhost:8125
    prefix: khan.
    tags_prefix: ""
    rate: 1
