// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  models

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Clan ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Clan ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Clan *Clan
