// +build ignore

// TEMPORARY AUTOGENERATED FILE: easyjson bootstapping code to launch
// the actual generator.

package main

import (
  "fmt"
  "os"

  "github.com/mailru/easyjson/gen"

  pkg "github.com/topfreegames/khan/models"
)

func main() {
  g := gen.NewGenerator("clan_easyjson.go")
  g.SetPkg("models", "github.com/topfreegames/khan/models")
  g.NoStdMarshalers()
  g.Add(pkg.EasyJSON_exporter_Clan(nil))
  if err := g.Run(os.Stdout); err != nil {
    fmt.Fprintln(os.Stderr, err)
    os.Exit(1)
  }
}
